"""Feature engineering — produces tabular features for ML and (samples, T, F) sequences for DL.

For the synthetic-data path, monthly weather sequences are generated by deterministically
expanding seasonal aggregates with seeded jitter — flagged in code below. When real
monthly NASA POWER series arrive, replace `_synthesise_weather_sequence` with a real reader.
"""

import os
import pickle
import numpy as np
import pandas as pd

from config import (
    ALL_FEATURES, WEATHER_FEATURES, SATELLITE_FEATURES,
    SEQUENCE_LENGTH, RANDOM_STATE, TARGET_COLUMN, N_WEATHER_PER_STEP,
)


def _synthesise_weather_sequence(row: pd.Series, rng: np.random.Generator) -> np.ndarray:
    """Expand seasonal aggregates into a (T, N_WEATHER_PER_STEP) monthly trajectory.

    Synthetic-only. Each timestep emits [temp, rainfall, humidity, solar_rad].
    Captures within-season variation (early-season cool/wet → mid-season warm/dry).
    """
    T = SEQUENCE_LENGTH
    temp = float(row['season_avg_temp'])
    rain = float(row['season_total_rainfall'])
    hum = float(row['season_avg_humidity'])
    solar = float(row['season_avg_solar_rad'])

    # Bell-shaped temperature with a peak mid-season.
    t_curve = np.array([temp + 1.5 * np.sin(np.pi * (i + 1) / (T + 1)) for i in range(T)])
    # Rainfall front-loaded slightly.
    r_weights = np.array([1.3, 1.1, 1.0, 0.9, 0.7])[:T]
    r_curve = (r_weights / r_weights.sum()) * rain
    h_curve = np.full(T, hum)
    s_curve = np.full(T, solar)

    noise = rng.normal(0, 0.02, size=(T, N_WEATHER_PER_STEP))
    seq = np.column_stack([t_curve, r_curve, h_curve, s_curve])
    seq = seq * (1 + noise)
    return seq.astype(np.float32)


def engineer_features(df: pd.DataFrame):
    print('\n' + '=' * 60)
    print('STEP 3: FEATURE ENGINEERING')
    print('=' * 60)

    df = df.copy()

    # Make sure all engineered features exist.
    feat_cols = [c for c in ALL_FEATURES if c in df.columns]
    missing = set(ALL_FEATURES) - set(feat_cols)
    if missing:
        print(f'  ⚠ Missing engineered features (will be omitted): {sorted(missing)}')

    X_tabular = df[feat_cols].astype(np.float32).values
    y = df[TARGET_COLUMN].astype(np.float32).values
    feature_names = feat_cols

    # Sequential weather data for LSTM / BiLSTM / hybrid CNN-LSTM.
    rng = np.random.default_rng(RANDOM_STATE)
    weather_seqs = np.stack(
        [_synthesise_weather_sequence(row, rng) for _, row in df.iterrows()],
        axis=0,
    )

    # Satellite "image" tensor for CNN branch — reshape SATELLITE_FEATURES to (N, F, 1).
    sat_cols = [c for c in SATELLITE_FEATURES if c in df.columns]
    X_satellite = df[sat_cols].astype(np.float32).values[:, :, None]

    # Season indicator scalar input (Yala=1, Maha=0).
    X_season = df['season_indicator'].astype(np.float32).values.reshape(-1, 1)

    # Persist.
    os.makedirs('data/processed', exist_ok=True)
    pd.DataFrame(X_tabular, columns=feature_names).assign(
        Year=df['Year'].values, Season=df['Season'].values,
        District=df['District'].values, **{TARGET_COLUMN: y},
    ).to_csv('data/processed/features_tabular.csv', index=False)

    seq_payload = {
        'weather_seq': weather_seqs,
        'satellite': X_satellite,
        'season': X_season,
        'y': y,
        'years': df['Year'].values,
        'districts': df['District'].values,
        'seasons': df['Season'].values,
        'satellite_feature_names': sat_cols,
        'weather_step_features': ['temp', 'rainfall', 'humidity', 'solar_rad'],
    }
    with open('data/processed/features_sequential.pkl', 'wb') as f:
        pickle.dump(seq_payload, f)

    print(f'  Tabular X: {X_tabular.shape} | y: {y.shape} | features: {len(feature_names)}')
    print(f'  Weather sequences: {weather_seqs.shape}')
    print(f'  Satellite tensor: {X_satellite.shape}')
    print('  Saved → data/processed/features_tabular.csv, features_sequential.pkl')

    return X_tabular, y, feature_names, seq_payload
